// Create Booking component
// User will input dates in local time, but it will show up as UTC

import { useState } from 'react';

const CreateBooking = ({ customers, backendURL, refreshBookings }) => {

    // Function to format local time to UTC
    // Generated by AI by prompting it to make a function to convert local time to UTC
    const convertToUTC = (dateStr) => {
        const date = new Date(dateStr);
        const year = date.getUTCFullYear();
        const month = String(date.getUTCMonth() + 1).padStart(2, '0');
        const day = String(date.getUTCDate()).padStart(2, '0');
        const hours = String(date.getUTCHours()).padStart(2, '0');
        const minutes = String(date.getUTCMinutes()).padStart(2, '0');
        const seconds = String(date.getUTCSeconds()).padStart(2, '0');

        return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
    };

    // Define the states
    const [customerID, setCustomerID] = useState("");
    const [bookingPrice, setPrice] = useState("");
    const [bookingDate, setDate] = useState("");

    // Handle changes to the form
    const handleChange = (e) => {
        // Get the name and value of the target form field that changed
        // name matches the name of the element
        const {name, value} = e.target;

        // Set the corresponding value based on what changed
        if (name === "customer_name") {
            setCustomerID(value);
        }

        if (name === "booking_price") {
            setPrice(value);
        }

        if (name === "booking_date") {
            setDate(value);
        }
    };

    // Function to clear the form after creating a booking
    const clearForm = async() => {
        setCustomerID("");
        setPrice("");
        setDate("");
    }

    // onSubmit to create the booking
    const handleSubmit = async (customerID, bookingPrice, bookingDate) => {

        // Convert the date from local time to UTC
        bookingDate = convertToUTC(bookingDate);

        // Create the object to send
        const data = {customerID, bookingPrice, bookingDate}

        // Create booking via POST request to /bookings
        try {
            const response = await fetch(backendURL + '/bookings', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data),
        });

        // Send alert and refresh the data on success
        if (response.status === 200) {
            alert(`Booking created. Make sure to create one or more tickets to link the booking to one or more flights`);
            refreshBookings();
            clearForm();
        } else {
            alert("Creation unsuccessful. Make sure price is a number.");
            console.error("Error creating customer.");
        }
        } catch (error) {
            alert("Creation unsuccessful");
            console.error('Error during form submission:', error);
        }
    };

    return (
        <>
        <h2>Create a Booking</h2>

        <form 
            className='bookingForm'
            onSubmit={(e) => {
                e.preventDefault();
                handleSubmit(customerID, bookingPrice, bookingDate)
            }}
        >
            <label htmlFor="customer_name">Customer Name: </label>
            <select
                name="customer_name"
                id="customer_name"
                value={customerID}
                onChange={handleChange}
            >
                {/* Customer ID is the value passed to onChange, and the corresponding name is displayed in the drop down */}
                <option value="">Select a Customer</option>
                {customers.map((customer, index) => (
                    <option value={customer["Customer ID"]} key={index}>{customer["Full Name"]}</option>
                ))}
            </select>

            <label htmlFor="booking_price">Booking Price: </label>
            <input
                type="text"
                name="booking_price"
                id="booking_price"
                value={bookingPrice}
                onChange={handleChange}
            />

            <label htmlFor="booking_date">Booking Date: </label>
            <input
                type="datetime-local"
                name="booking_date"
                id="booking_date"
                value={bookingDate}
                onChange={handleChange}
            />

            <input type="submit" value="Create Booking"/>

        </form>
        </>
    );
};

export default CreateBooking;