// CreateFlight Component

import { useState } from 'react';

const CreateFlight = ({ airplanes, backendURL, refreshFlights }) => {

    // Function to find an airplane id given an airplane model
    const findAirplaneID = (airplaneModel) => {
        const airplane = airplanes.find((airplane) => airplane["Airplane Model"] === airplaneModel);

        // Returns airplane id if an airplane object is found that matches the model
        return airplane ? airplane["Airplane ID"] : "";
    }

    // Function to format local time to UTC
    // Generated by AI by prompting it to make a function to convert local time to UTC
    const convertToUTC = (dateStr) => {
        const date = new Date(dateStr);
        const year = date.getUTCFullYear();
        const month = String(date.getUTCMonth() + 1).padStart(2, '0');
        const day = String(date.getUTCDate()).padStart(2, '0');
        const hours = String(date.getUTCHours()).padStart(2, '0');
        const minutes = String(date.getUTCMinutes()).padStart(2, '0');
        const seconds = String(date.getUTCSeconds()).padStart(2, '0');

        return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
    };

    // Define the states
    const [selectedAirplaneModel, setSelectedModel] = useState("");
    const [selectedDepartureCity, setSelectedDepartureCity] = useState("");
    const [selectedArrivalCity, setSelectedArrivalCity] = useState("");
    const [selectedDepartureTime, setSelectedDepartureTime] = useState("");
    const [selectedArrivalTime, setSelectedArrivalTime] = useState("");
    const [selectedFlightStatus, setSelectedFlightStatus] = useState("");
    const [selectedSeats, setSelectedSeats] = useState("");
    const [selectedAirplaneID, setSelectedAirplaneID] = useState("");

    // Handle input changes in the form
    const handleChange = (e) => {
        const {name, value} = e.target;

        // Set the model and corresponding airplane id
        if (name === "airplane_model") {
            setSelectedModel(value);
            setSelectedAirplaneID(findAirplaneID(value));            
        }

        // Set departure city to be from the form
        if (name === "flight_depart_city") {
            setSelectedDepartureCity(value);
        }

        // Set arrival city
        if (name === "flight_arrival_city") {
            setSelectedArrivalCity(value);
        }

        // Set departure time
        if (name === "flight_departure_time") {
            setSelectedDepartureTime(value);
        }

        // Set arrival time
        if (name === "flight_arrival_time") {
            setSelectedArrivalTime(value);
        }

        // Set flight status
        if (name === "flight_status") {
            setSelectedFlightStatus(value);
        }

        // Set available seats
        if (name === "flight_avail_seats") {
            setSelectedSeats(value);
        }
    }

    // Function to clear the form after creating a flight
    const clearForm = async() => {
        setSelectedDepartureCity("");
        setSelectedArrivalCity("");
        setSelectedDepartureTime("");
        setSelectedArrivalTime("");
        setSelectedModel("");
        setSelectedAirplaneID("");
        setSelectedFlightStatus("");
        setSelectedSeats("");
    }

    // Function to call the create procedure
    // Requires: airplane_id which is the airplane id corresponding to the model
    //           departure_city which is the 3 letter code of the city
    //           arrival_city which is the 3 letter code of the city
    //           departure_time which corresponds to the time of departure
    //           arrival_time which corresponds to the time of arrival
    //           flight_status which corresponds to the status of the flight
    //           available_seats which corresponds to the remaining available seats in the particular flight
    const onCreate = async (airplane_id, departure_city, arrival_city,
                            departure_time, arrival_time, flight_status, available_seats) => {
            
        // Convert local datetime strings to UTC ISO strings for the database
        departure_time = convertToUTC(departure_time);
        arrival_time = convertToUTC(arrival_time);

        // Create the object to send. Key/values are the parameters passed
        const data = {airplane_id, departure_city, arrival_city, departure_time, arrival_time, flight_status, available_seats}

        // Send a POST request to /flights url in the backend
        const response = await fetch(`${backendURL}/flights`, {
            method: "POST",
            headers: {"Content-type": "application/json"},
            body: JSON.stringify(data)
        });

        // If the request was successful, refresh the data after confirmation
        if (response.status === 200) {
            alert("Data successfully created");
            refreshFlights();
            clearForm();
        }
        else {
            alert("Creation unsuccessful. Make sure the city codes are valid inputs.");
            console.error(`status code = ${response.status}`);
        }
    }

    return (
        <>
        <h2>Create a Flight</h2>

        <form 
            className='flightForm'
            onSubmit={(e) => {
                e.preventDefault();
                onCreate(selectedAirplaneID, selectedDepartureCity, selectedArrivalCity,
                    selectedDepartureTime, selectedArrivalTime, selectedFlightStatus, selectedSeats);
            }}
        >
            <label htmlFor="flight_depart_city">Departure City: </label>
            <input
                type="text"
                name="flight_depart_city"
                id="flight_depart_city"
                value={selectedDepartureCity}
                onChange={handleChange}
            />

            <label htmlFor="flight_arrival_city">Arrival City: </label>
            <input
                type="text"
                name="flight_arrival_city"
                id="flight_arrival_city"
                value={selectedArrivalCity}
                onChange={handleChange}
            />

            <label htmlFor="flight_departure_time">Departure Time: </label>
            <input
                type="datetime-local"
                name="flight_departure_time"
                id="flight_departure_time"
                value={selectedDepartureTime}
                onChange={handleChange}
            />

            <label htmlFor="flight_arrival_time">Arrival Time: </label>
            <input
                type="datetime-local"
                name="flight_arrival_time"
                id="flight_arrival_time"
                value={selectedArrivalTime}
                onChange={handleChange}
            />
            
            <p></p>

            <label htmlFor="airplane_model">Airplane Model: </label>
            <select
                name="airplane_model"
                id="airplane_model"
                value={selectedAirplaneModel}
                onChange={handleChange}
            >
                <option value="">Select a Plane</option>
                {airplanes.map((airplane, index) => (
                    <option value={airplane["Airplane Model"]} key={index}>{airplane["Airplane Model"]}</option>
                ))}
            </select>

            <label htmlFor="flight_status">Flight Status: </label>
            <select
                name="flight_status"
                id="flight_status"
                value={selectedFlightStatus}
                onChange={handleChange}
            >
                <option value="ON SCHEDULE">ON SCHEDULE</option>
                <option value="DELAYED">DELAYED</option>
                <option value="ARRIVED">ARRIVED</option>
            </select>

            <label htmlFor="flight_avail_seats">Available Seats: </label>
            <input
                type="number"
                name="flight_avail_seats"
                id="flight_avail_seats"
                value={selectedSeats}
                onChange={handleChange}
            />

            <input type="submit" value="Create Flight" />
        </form>
        </>
    );
};

export default CreateFlight;